Added edition-specific configuration
ezsystems/BehatBundle pull request #174
Opened 2021-02-23 14:36 UTC by mnocon

2021-03-08 10:28 UTC, bogusez commented
@mnocon in this PR we also need additional spaces. It occurs in several lines for example 69.

2021-03-08 10:28 UTC, bogusez requested changes

2021-03-08 10:28 UTC, bogusez commented on .travis.yml
> +  - if [ "${SETUP_BEHAT_OPTS}" != "" ]; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "vendor/bin/ezbehat $SETUP_BEHAT_OPTS" ; fi
space needed

2021-03-08 10:32 UTC, mnocon commented on .travis.yml
> +  - if [ "${SETUP_BEHAT_OPTS}" != "" ]; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "vendor/bin/ezbehat $SETUP_BEHAT_OPTS" ; fi
Fixed in https://github.com/ezsystems/BehatBundle/pull/174/commits/586390935621b742d0135c30dc5b99bc49246186

2021-03-08 10:37 UTC, bogusez approved these changes

2021-03-10 07:42 UTC, micszo approved these changes
Thanks! 💪

2021-03-10 08:38 UTC, merged